[workspace]
members = ["livre-derive"]

[package]
name = "livre"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.6"

enum_dispatch = "0.3"

# Filtering
flate2 = "1"

paste = "1"
livre-derive = { path = "./livre-derive" }

[dev-dependencies]
rstest = "0.22"
