[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1.0.57"

[dev-dependencies]
indoc = "2.0.4"
