[workspace]
resolver = "2"
members = [
    "livre-utilities",
    "livre-filters",
    "livre-extraction",
    "livre-derive",
    "livre-objects",
    "livre-data",
    "livre-structure",
    "livre-document",
    "livre-text",
    "livre-fonts",
    "livre-serde",
]
