[package]
name = "livre-extraction"
version = "0.1.0"
edition = "2021"


[dependencies]
nom = "7"

thiserror = "1"

paste = "1"

livre-derive = { path = "../livre-derive" }
livre-utilities = { path = "../livre-utilities" }

serde = "1"

[dev-dependencies]
rstest = "0.21"
