[package]
name = "livre-extraction"
version = "0.1.0"
edition = "2021"


[dependencies]
nom = "7"

thiserror = "1.0"

paste = "1.0"

livre-derive = { path = "../livre-derive" }
livre-utilities = { path = "../livre-utilities" }
serde = "1.0.204"

[dev-dependencies]
rstest = "0.18.2"
