[package]
name = "livre"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
serde = { version = "1", features = ["derive"] }

flate2 = "1"

enum_dispatch = "0.3"
itertools = "0.13"

thiserror = "1"

paste = "1"

[dev-dependencies]
rstest = "0.21"
indoc = "2"
