[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lib]
name = "livre_python"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
livre = { path = ".." }

pyo3 = "0.22"
